name: Cancel
on: [push]
permissions:
  actions: write
jobs:
  cancel:
    name: "Cancel Previous Build"
    if: github.workflow != 'Cancel'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          workflow_id: ".github/workflows/flow1.yml,.github/workflows/flow2.yml"
          all_but_latest: true
          access_token: ${{ github.token }}
