name: Sleep for 90 seconds

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-timeout:
    name: Sleep job
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Sleep for 90 seconds
        run: sleep 90
